[package]
name = "hemlc"
version = "0.0.33"
edition = "2024"
description = "Compiler for HEML (Hyperextended Markup Language): HTML plus imports, components and control flow"
license = "MIT"

[[bin]]
name = "hemlc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
notify = "8.2.0"
rand = "0.10.2"
self_update = { version = "0.44", features = ["archive-tar", "compression-flate2", "rustls"] }

[build-dependencies]
minify-js = "0.6.0"

[profile.release]
lto = true
strip = true
