use crate::{compiler::codegen::{types::{CodegenStrategy, Compiler}, util}, core::types::Attrs};

pub trait HtmlGenerator {
    fn user_script_block(&self, content: &str) -> String;
    fn main_js_block(&self, script: &str) -> String;
    fn core_js_block(&self, script: &str) -> String;
    fn generate_comment(&self, comment:&str) -> String;
}

impl HtmlGenerator for Compiler {
    fn main_js_block(&self, script: &str) -> String {
        match self.options.codegen_strategy {
            CodegenStrategy::AsIs => format!(
"
<!-- Autogenerated compiled JS utility for reactivity -->
<script>
    {}
</script>
",
                script
            ),
            CodegenStrategy::MinifyJsOnly | CodegenStrategy::MinifyAll => {
                format!("<script>{}</script>", script)
            }
        }
    }

    fn user_script_block(&self, content: &str) -> String {
        match self.options.codegen_strategy {
            CodegenStrategy::AsIs => format!(
    "
    (
        (document) => {{
            {}
        }})(new Proxy(
            document, {{ 
                get(target, prop) {{
                    if (prop === 'getElementById')
                        {{
                            return (id) => frag.querySelector(`[id=\"${{id}}\"]`);
                        }}
                    if (prop === 'querySelector' || prop === 'querySelectorAll') {{
                        return frag[prop].bind(frag);
                    }}
                    const val = target[prop];
                    return typeof val === 'function' ? val.bind(target) : val;
                }}
            }}
        )
    );
    ",
                content
            ),
            CodegenStrategy::MinifyAll | CodegenStrategy::MinifyJsOnly => format!(
                "((document) => {{{}}})(new Proxy(document,{{get(target,prop){{if(prop==='getElementById'){{return (id)=>frag.querySelector(`[id=\"${{id}}\"]`);}}if(prop==='querySelector'||prop==='querySelectorAll'){{return frag[prop].bind(frag);}}const val=target[prop];return typeof val==='function'?val.bind(target):val;}}}}));",
                content
            ),
        }
    }

    fn core_js_block(&self, script: &str) -> String {
        match self.options.codegen_strategy {
            CodegenStrategy::AsIs => format!(
"
<!-- Injected core.min.js - for basic reactive utility -->
<script>
    {}
</script>
",
                script
            ),
            CodegenStrategy::MinifyAll | CodegenStrategy::MinifyJsOnly => format!(
                "<script>{}</script>",
                script
            ),
        }
    }
    
    fn generate_comment(&self, comment:&str) -> String {
        if self.options.codegen_strategy != CodegenStrategy::MinifyAll {
            format!("<!--{}-->", comment)
        }else {
            String::new()
        }
    }
}

/// Builds something like this `<myTag ...>` or `<myTag .../>` (if it is void) with their respective attribtues.
pub fn build_open_tag(tag: &str, attrs: &Attrs, is_void: bool) -> String {
    if attrs.is_empty() {
        if is_void {
            format!("<{}/>", tag)
        } else {
            format!("<{}>", tag)
        }
    } else {
        let attrs = util::generate_html_from_attrs(attrs);
        if is_void {
            format!("<{} {}/>", tag, attrs)
        } else {
            format!("<{} {}>", tag, attrs)
        }
    }
}

pub fn generate_doctype(doctype: &str) -> String {
    return format!("<!DOCTYPE {}>", if doctype.eq_ignore_ascii_case("heml") {"html"} else {doctype})
}

pub fn generate_closing_tag(tag_name: &str) -> String {
    return format!("</{}>", tag_name)
}