use crate::{compiler::codegen::types::{CodegenStrategy, Compiler}, core::types::Attrs};

pub trait HtmlGenerator {
    fn user_script_block(&self, content: &str) -> String;
    fn main_js_block(&self, script: &str) -> String;
    fn core_js_block(&self, script: &str) -> String;
}

impl HtmlGenerator for Compiler {
    fn main_js_block(&self, script: &str) -> String {
        match self.options.codegen_strategy {
            CodegenStrategy::AsIs => format!(
"
<!-- Autogenerated compiled JS utility for reactivity -->
<script>
    {}
</script>
",
                script
            ),
            CodegenStrategy::MinifyJsOnly | CodegenStrategy::MinifyAll => {
                format!("<script>{}</script>", script)
            }
        }
    }

    fn user_script_block(&self, content: &str) -> String {
        match self.options.codegen_strategy {
            CodegenStrategy::AsIs => format!(
    "
    (
        (document) => {{
            {}
        }})(new Proxy(
            document, {{ 
                get(target, prop) {{
                    if (prop === 'getElementById')
                        {{
                            return (id) => frag.querySelector(`[id=\"${{id}}\"]`);
                        }}
                    if (prop === 'querySelector' || prop === 'querySelectorAll') {{
                        return frag[prop].bind(frag);
                    }}
                    const val = target[prop];
                    return typeof val === 'function' ? val.bind(target) : val;
                }}
            }}
        )
    );
    ",
                content
            ),
            CodegenStrategy::MinifyAll | CodegenStrategy::MinifyJsOnly => format!(
                "((document) => {{{}}})(new Proxy(document,{{get(target,prop){{if(prop==='getElementById'){{return (id)=>frag.querySelector(`[id=\"${{id}}\"]`);}}if(prop==='querySelector'||prop==='querySelectorAll'){{return frag[prop].bind(frag);}}const val=target[prop];return typeof val==='function'?val.bind(target):val;}}}}));",
                content
            ),
        }
    }

    fn core_js_block(&self, script: &str) -> String {
        match self.options.codegen_strategy {
            CodegenStrategy::AsIs => format!(
"
<!-- Injected core.min.js - for basic reactive utility -->
<script>
    {}
</script>
",
                script
            ),
            CodegenStrategy::MinifyAll | CodegenStrategy::MinifyJsOnly => format!(
                "<script>{}</script>",
                script
            ),
        }
    }
}

pub fn generate_html_from_attrs(attrs: &Attrs) -> String {
    let mut buffer = String::new();
    for (key, val) in attrs.iter() {
        buffer += key.as_str();
        if let Some(val) = val {
            buffer += &format!("=\"{}\" ", val.as_str());
        } else {
            buffer += " ";
        }
    }
    buffer.trim_end().to_string()
}